로그인 기능 구현
wecode-bootcamp-korea/33-1st-CatCoDog-backend pull request #5
Opened 2022-05-26 07:11 UTC by HighandLight

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 로그인 기능 구현

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. bcrypt로 비밀번호 확인
2. 로그인시 jwt로 토큰 발급
3. 토큰 만료시간은 1일이며 변수로 변경 가능
4. 차후 활용을 위해 utils.py에 login_decorator 추가

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 토큰 만료시간을 설정하는 방법을 배웠습니다. 

<br />

## :: 기타 질문 및 특이 사항
- 개선사항 있다면 피드백 부탁드립니다.

2022-05-26 09:37 UTC, Kang-kyunghun requested changes

2022-05-26 09:37 UTC, Kang-kyunghun commented on users/utils.py
> +from django.conf import settings
```suggestion
from datetime import datetime
import re, jwt

from django.http import JsonResponse
from users.models import User

from django.conf import settings
```
import 컨벤션에 맞게 수정해 주세요.

2022-05-26 09:37 UTC, Kang-kyunghun commented on users/views.py
> +                            )
아래와 같이 import 순서를 지켜주면 좋을 것 같습니다.
```python
#Standard library imports.
import json 
from datetime import datetime, timedelta

#Related third party imports.
import bcrypt
import jwt
from django.http  import JsonResponse
from django.views import View
from django.conf  import settings

#Local application/library specific imports.
from users.models import User, PetType
from users.utils  import (
    validate_name,
    validate_email,
    validate_password,
    validate_mobile_number,
    login_decorator,
)

```

2022-05-26 09:38 UTC, Kang-kyunghun commented
로직 부분은 괜찮은 것 같습니다. 리뷰 부분 수정하면 바로 merge 하겠습니다.

2022-05-26 10:51 UTC, HighandLight commented
네 피드백 반영해서 import문 순서 수정했습니다!!

2022-05-27 01:07 UTC, Kang-kyunghun commented
LGTM~!

2022-05-27 01:07 UTC, merged